package com.lingfly.mqttclient.dao;

import com.lingfly.mqttclient.entity.Content;
import com.lingfly.mqttclient.entity.ContentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ContentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content
     *
     * @mbg.generated Fri Apr 24 13:07:16 CST 2020
     */
    long countByExample(ContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content
     *
     * @mbg.generated Fri Apr 24 13:07:16 CST 2020
     */
    int deleteByExample(ContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content
     *
     * @mbg.generated Fri Apr 24 13:07:16 CST 2020
     */
    int insert(Content record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content
     *
     * @mbg.generated Fri Apr 24 13:07:16 CST 2020
     */
    int insertSelective(Content record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content
     *
     * @mbg.generated Fri Apr 24 13:07:16 CST 2020
     */
    List<Content> selectByExample(ContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content
     *
     * @mbg.generated Fri Apr 24 13:07:16 CST 2020
     */
    int updateByExampleSelective(@Param("record") Content record, @Param("example") ContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content
     *
     * @mbg.generated Fri Apr 24 13:07:16 CST 2020
     */
    int updateByExample(@Param("record") Content record, @Param("example") ContentExample example);
}