package com.lingfly.mqttclient.dao;

import com.lingfly.mqttclient.entity.Friends;
import com.lingfly.mqttclient.entity.FriendsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FriendsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friends
     *
     * @mbg.generated Fri Apr 24 13:07:16 CST 2020
     */
    long countByExample(FriendsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friends
     *
     * @mbg.generated Fri Apr 24 13:07:16 CST 2020
     */
    int deleteByExample(FriendsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friends
     *
     * @mbg.generated Fri Apr 24 13:07:16 CST 2020
     */
    int insert(Friends record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friends
     *
     * @mbg.generated Fri Apr 24 13:07:16 CST 2020
     */
    int insertSelective(Friends record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friends
     *
     * @mbg.generated Fri Apr 24 13:07:16 CST 2020
     */
    List<Friends> selectByExample(FriendsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friends
     *
     * @mbg.generated Fri Apr 24 13:07:16 CST 2020
     */
    int updateByExampleSelective(@Param("record") Friends record, @Param("example") FriendsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friends
     *
     * @mbg.generated Fri Apr 24 13:07:16 CST 2020
     */
    int updateByExample(@Param("record") Friends record, @Param("example") FriendsExample example);
}