package com.lingfly.mqttclient.entity;

public class Content {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content.from_user
     *
     * @mbg.generated Fri Apr 24 13:07:16 CST 2020
     */
    private String fromUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content.to_user
     *
     * @mbg.generated Fri Apr 24 13:07:16 CST 2020
     */
    private String toUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content.msg
     *
     * @mbg.generated Fri Apr 24 13:07:16 CST 2020
     */
    private String msg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content.type
     *
     * @mbg.generated Fri Apr 24 13:07:16 CST 2020
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content.friend
     *
     * @mbg.generated Fri Apr 24 13:07:16 CST 2020
     */
    private String friend;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content.from_user
     *
     * @return the value of content.from_user
     *
     * @mbg.generated Fri Apr 24 13:07:16 CST 2020
     */
    public String getFromUser() {
        return fromUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content.from_user
     *
     * @param fromUser the value for content.from_user
     *
     * @mbg.generated Fri Apr 24 13:07:16 CST 2020
     */
    public void setFromUser(String fromUser) {
        this.fromUser = fromUser == null ? null : fromUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content.to_user
     *
     * @return the value of content.to_user
     *
     * @mbg.generated Fri Apr 24 13:07:16 CST 2020
     */
    public String getToUser() {
        return toUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content.to_user
     *
     * @param toUser the value for content.to_user
     *
     * @mbg.generated Fri Apr 24 13:07:16 CST 2020
     */
    public void setToUser(String toUser) {
        this.toUser = toUser == null ? null : toUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content.msg
     *
     * @return the value of content.msg
     *
     * @mbg.generated Fri Apr 24 13:07:16 CST 2020
     */
    public String getMsg() {
        return msg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content.msg
     *
     * @param msg the value for content.msg
     *
     * @mbg.generated Fri Apr 24 13:07:16 CST 2020
     */
    public void setMsg(String msg) {
        this.msg = msg == null ? null : msg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content.type
     *
     * @return the value of content.type
     *
     * @mbg.generated Fri Apr 24 13:07:16 CST 2020
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content.type
     *
     * @param type the value for content.type
     *
     * @mbg.generated Fri Apr 24 13:07:16 CST 2020
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content.friend
     *
     * @return the value of content.friend
     *
     * @mbg.generated Fri Apr 24 13:07:16 CST 2020
     */
    public String getFriend() {
        return friend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content.friend
     *
     * @param friend the value for content.friend
     *
     * @mbg.generated Fri Apr 24 13:07:16 CST 2020
     */
    public void setFriend(String friend) {
        this.friend = friend == null ? null : friend.trim();
    }
}