package com.lingfly.mqttclient.entity;

public class Friends {
    public Friends() {
    }

    public Friends(String name, String friend) {
        this.name = name;
        this.friend = friend;
    }
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friends.name
     *
     * @mbg.generated Fri Apr 24 13:07:16 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friends.friend
     *
     * @mbg.generated Fri Apr 24 13:07:16 CST 2020
     */
    private String friend;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friends.name
     *
     * @return the value of friends.name
     *
     * @mbg.generated Fri Apr 24 13:07:16 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friends.name
     *
     * @param name the value for friends.name
     *
     * @mbg.generated Fri Apr 24 13:07:16 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friends.friend
     *
     * @return the value of friends.friend
     *
     * @mbg.generated Fri Apr 24 13:07:16 CST 2020
     */
    public String getFriend() {
        return friend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friends.friend
     *
     * @param friend the value for friends.friend
     *
     * @mbg.generated Fri Apr 24 13:07:16 CST 2020
     */
    public void setFriend(String friend) {
        this.friend = friend == null ? null : friend.trim();
    }
}