package com.lingfly.mqttclient.entity;

import java.util.Date;
import java.util.List;

public class Message {
    private List<String> friends;

    private List<String> allFriend;

    private String friend;

    public List<String> getFriends() {
        return friends;
    }

    public void setFriends(List<String> friends) {
        this.friends = friends;
    }

    public List<String> getAllFriend() {
        return allFriend;
    }

    public void setAllFriend(List<String> allFriend) {
        this.allFriend = allFriend;
    }

    public String getFriend() {
        return friend;
    }

    public void setFriend(String friend) {
        this.friend = friend;
    }
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.msg_id
     *
     * @mbg.generated Fri Apr 24 13:07:16 CST 2020
     */
    private Integer msgId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.send_msg
     *
     * @mbg.generated Fri Apr 24 13:07:16 CST 2020
     */
    private String sendMsg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.from_user
     *
     * @mbg.generated Fri Apr 24 13:07:16 CST 2020
     */
    private String fromUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.to_user
     *
     * @mbg.generated Fri Apr 24 13:07:16 CST 2020
     */
    private String toUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.is_send
     *
     * @mbg.generated Fri Apr 24 13:07:16 CST 2020
     */
    private Integer isSend;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.date
     *
     * @mbg.generated Fri Apr 24 13:07:16 CST 2020
     */
    private Date date;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.msg_id
     *
     * @return the value of message.msg_id
     *
     * @mbg.generated Fri Apr 24 13:07:16 CST 2020
     */
    public Integer getMsgId() {
        return msgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.msg_id
     *
     * @param msgId the value for message.msg_id
     *
     * @mbg.generated Fri Apr 24 13:07:16 CST 2020
     */
    public void setMsgId(Integer msgId) {
        this.msgId = msgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.send_msg
     *
     * @return the value of message.send_msg
     *
     * @mbg.generated Fri Apr 24 13:07:16 CST 2020
     */
    public String getSendMsg() {
        return sendMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.send_msg
     *
     * @param sendMsg the value for message.send_msg
     *
     * @mbg.generated Fri Apr 24 13:07:16 CST 2020
     */
    public void setSendMsg(String sendMsg) {
        this.sendMsg = sendMsg == null ? null : sendMsg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.from_user
     *
     * @return the value of message.from_user
     *
     * @mbg.generated Fri Apr 24 13:07:16 CST 2020
     */
    public String getFromUser() {
        return fromUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.from_user
     *
     * @param fromUser the value for message.from_user
     *
     * @mbg.generated Fri Apr 24 13:07:16 CST 2020
     */
    public void setFromUser(String fromUser) {
        this.fromUser = fromUser == null ? null : fromUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.to_user
     *
     * @return the value of message.to_user
     *
     * @mbg.generated Fri Apr 24 13:07:16 CST 2020
     */
    public String getToUser() {
        return toUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.to_user
     *
     * @param toUser the value for message.to_user
     *
     * @mbg.generated Fri Apr 24 13:07:16 CST 2020
     */
    public void setToUser(String toUser) {
        this.toUser = toUser == null ? null : toUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.is_send
     *
     * @return the value of message.is_send
     *
     * @mbg.generated Fri Apr 24 13:07:16 CST 2020
     */
    public Integer getIsSend() {
        return isSend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.is_send
     *
     * @param isSend the value for message.is_send
     *
     * @mbg.generated Fri Apr 24 13:07:16 CST 2020
     */
    public void setIsSend(Integer isSend) {
        this.isSend = isSend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.date
     *
     * @return the value of message.date
     *
     * @mbg.generated Fri Apr 24 13:07:16 CST 2020
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.date
     *
     * @param date the value for message.date
     *
     * @mbg.generated Fri Apr 24 13:07:16 CST 2020
     */
    public void setDate(Date date) {
        this.date = date;
    }
}